### ISSUE TITLE
Buena solución a tu idea, pero hay otra más

### ISSUE THREAD

**Issue by whitehatdevv** [iBigBitDev97/Excuse-generator-arrays#1]
https://github.com/iBigBitDev97/Excuse-generator-arrays/blob/58a84c79291e274fde61492c731e9222d3d11506/index.js#L33

Una de las soluciones por la que podías haber obtado y de hecho debería haber sido la que hubieses elegido por limpieza sería la siguiente:

 ```js
response +=  `${arr1[randomNumber(arr1)]} `; 
```

Usando la interporlación de String queda mucho más limpio. Por otra parte ten cuidado con el indentado del codigo.
PD: Están genial los ejercicios :)

**Comment by iBigBitDev97** [comment]
Arreglado los espacios
